// Auto-generated mapping data. Edit if needed.
window.RUT_AGF_MAP = {
  "084177300-4": "CELFIN Capital",
  "061808000-5": "Aguas Andinas S.A.",
  "076012676-4": "SMU S.A.",
  "076017019-4": "Mall Plaza S.A.",
  "076433310-1": "Cencosud Shopping S.A.",
  "088006900-4": "Enel Américas S.A. (ECL)",
  "089862200-2": "LATAM Airlines (LTM)",
  "090222000-3": "CMPC S.A.",
  "090227000-0": "Viña Concha y Toro S.A.",
  "090413000-1": "CCU S.A.",
  "090690000-9": "Copec S.A.",
  "090749000-9": "Falabella S.A.",
  "091144000-8": "Andina S.A.",
  "091297000-0": "CAP S.A.",
  "091705000-7": "Quiñenco S.A.",
  "093834000-5": "Cencosud S.A.",
  "094627000-8": "Parque Arauco S.A.",
  "096505760-9": "Colbún S.A.",
  "097004000-5": "Banco de Chile S.A.",
  "097006000-6": "Banco BCI S.A.",
  "099579730-5": "Ripley Corp S.A.",
  "076034728-0": "HMC S.A. AGF",
  "076172904-7": "Asset Chile AGF (Rentas)",
  "076503273-3": "Ameris Capital AGF",
  "096684990-8": "Moneda AGF",
  "076081215-3": "Larraín Vial Activos AGF",
  "076493189-0": "VolcomCapital AGF",
  "096955500-K": "LarraínVial AGF",
  "096966250-7": "BTG Pactual Chile AGF",
  "094271000-3": "Enel Américas S.A.",
  "096970380-7": "Enjoy S.A.",
  "076989262-1": "Inmobiliaria Pedro Luna S.P.A.",
  "077389075-7": "Norteverde S.A.",
  "076028139-5": "Ameris BIM Capital AGF",
  "076543031-3": "Frontal Trust AGF",
  "077087811-K": "WEG Chile AGF",
  "077652483-2": "Nvida AGF",
  "096530900-4": "BCI Asset Management AGF",
  "096632170-9": "Penta Las Américas AGF",
  "096690790-8": "Principal AGF",
  "096753330-0": "Renta Nacional AGF",
  "096804330-7": "Compass Group Chile AGF",
  "076392725-3": "FIP Avocado A",
  "077274677-6": "Fondo de Inversión Privado Wellcorp",
  "076963034-1": "Link Capital Partners AGF",
  "096514410-2": "BICE Inversiones AGF",
  "099549940-1": "Credicorp Capital AGF",
  "076435792-2": "Capital Advisors AGF",
  "076579033-6": "XLC AGF",
  "096667040-1": "Santander Asset Mgmt. AGF",
  "076184068-1": "Nitratos y Fertilizantes S.A.",
  "092544000-0": "Cintac S.A.",
  "093007000-9": "SQM S.A.",
  "096511530-7": "Soc. de Inv. Oro Blanco (Calichera)",
  "096529340-K": "NorteGrande S.A.",
  "096532830-0": "Oro Blanco S.A.",
  "096666140-2": "DCV Vida S.A. (alt.)",
  "099503280-5": "Intasa S.A.",
  "096576660-K": "Toesca AGF",
  "099543100-9": "MBI AGF",
  "000000001-9": "Las Américas Infraestructura AGF",
  "096658670-2": "DCV Vida S.A. (alt.)",
  "000009501-K": "BTG Pactual (registro antiguo)",
  "076328507-3": "Asset Chile AGF (Rentas)",
  "076036521-1": "SURA AGF",
  "097036000-K": "BSANTANDER",
  "096767630-6": "Banchile AGF",
  "076917333-1": "Singular Asset Management AGF",
  "076507811-3": "Falcom AGF",
  "076122579-0": "Neorentas AGF",
  "076202136-6": "Picton AGF",
  "096980650-9": "Itaú Chile AGF",
  "076798260-7": "Quest Capital AGF",
  "076503272-5": "WEG Chile AGF",
  "077157847-0": "Doctor Sierra S.A.",
  "094046000-K": "Egeco S.A.",
  "076536353-5": "Enel Chile S.A.",
  "092580000-7": "Entel S.A.",
  "077447468-4": "Fondo de Inversión Privado Aconcagua",
  "076522369-5": "Andes III Fondo de Inversión Privado",
  "077274820-5": "IAM S.A.",
  "076039786-5": "Inversiones Inmobiliarias Seguras S.A.",
  "076021066-8": "Nmobiliaria Valle Del Mar Etap",
  "097023000-9": "Itaú CorpBanca S.A.",
  "096782380-5": "Montemar Marítima S.A.",
  "078075573-3": "Nueva Chamisera S.A.",
  "077190843-8": "Plaza Granadilla S.A.",
  "096885880-7": "Salfacorp S.A.",
  "090160000-7": "Empresa Nav. Vapores S.A.",
  "077073978-0": "Vivo Santiago S.A.",
  "076578803-K": "Ameris Capital AGF (alt.)",
  "076708560-5": "Banchile Inversiones AGF",
  "094270000-8": "Almendral S.A.",
  "096561560-1": "Pucobre S.A.",
  "076618543-6": "INMOBILIARIA SANTA MONICA S.P.A.",
  "077067086-1": "INMOBILIARIA ESTOCOLMO FORTALEZA SPA.",
  "091999000-7": "Principal AGF",
  "094139000-5": "ILC S.A.",
  "077442503-9": "Fondo de Inversión Privado Ecomac",
  "076825295-5": "INM VILENA",
  "076800464-1": "INM IRARRAZAVAL",
  "077389291-1": "INM MACKENNA",
  "077952328-4": "INM ED VICTORIA",
  "077967313-8": "INMOBILIARIA LF SPA",
  "077303392-7": "INM ECOMAC N1",
  "096844470-0": "Piedra Roja Desarrollos S.A.",
  "076966850-0": "INM VVALDE",
  "076836800-7": "INM BBI",
  "076975641-8": "INM ROBLES",
  "076351982-1": "INM RRIO",
  "077113019-4": "INM ZANARTU",
  "077087963-9": "INM LOMAS QUILIN",
  "077114596-5": "INM VICMACK",
  "077765165-K": "INM LA CASTELLANA",
  "077894984-9": "INM MIRAFLORES",
  "077716154-7": "INM ECOMAC N16",
  "077562117-6": "INM ECOMAC N7",
  "077884278-5": "INM VINEDOS BUIN",
  "085741000-9": "BICE S.A.",
  "093281000-K": "Embonor S.A.",
  "076349271-0": "Río San Pedro S.A.",
  "076449357-5": "Plaza Egaña S.A.",
  "076587907-8": "Nucleo Trapezoidal S.A.",
  "076994092-8": "Torremayorv S.A.",
  "076071197-7": "Fynsa AGF",
  "096639280-0": "Security AGF",
  "076245696-6": "Ameris Multifamily Partners Fi",
  "076107002-9": "HMC - Rentas Vida Parque FIP",
  "076109533-1": "Fondo de Inversión Privado IPA",
  "076166419-0": "Fondo de Inversión Privado KMA",
  "076318003-4": "Fondo de Inversión Privado El",
  "076616632-6": "Fondo de Inversión Privado Est",
  "076309510-K": "Enlasa Generación S.A.",
  "076066448-0": "Exynko S.A.",
  "096778070-7": "Penta MH S.A.",
  "076277884-K": "FIP Fen Ventures II",
  "076477116-8": "CF Seguros de Vida S.A.",
  "096874030-K": "ABC DINA S.A.",
  "077333224-K": "Deuda Privada VI AGF",
  "096601710-4": "Inciment AGF",
  "076416293-5": "INMOBILIARIA MONTE SANTO 3 S.P.A.",
  "076468394-3": "INMOBILIARIA ALTO RELONCAVI S.A.",
  "076576572-2": "INMOBILIARIA VIA PONIENTE S.A.",
  "099591340-2": "INMOBILIARIA LOS NAVEGANTES S.A.",
  "076318228-2": "INMOBILIARIA AGUAS CLARAS S.P.A.",
  "076326533-1": "INMOBILIARIA EDIFICIOS DE HACIENDA S.P.A.",
  "076882093-7": "INMOBILIARIA ALTO TABANCURA SPA",
  "077094393-0": "INMOBILIARIA QUEBRADA CLARA SPA",
  "077290472-K": "INMOBILIARIA DIEGO DE ALMAGRO SPA",
  "077433282-0": "DESARROLLOS INDUSTRIALES TRES SPA.",
  "076455482-5": "INMOBILIARIA LOS ROBLES S.P.A.",
  "076453436-0": "INMOBILIARIA VILLA PACIFICO S.P.A.",
  "076882227-1": "INMOBILIARIA PARQUE TORREONES S.P.A.",
  "076948771-9": "INMOBILIARIA PRIMEPARK CURAUMA S.P.A.",
  "077006764-2": "INMOBILIARIA SANTA MARTA S.P.A.",
  "077172710-7": "INVERSIONES EL PINAR SPA",
  "076515767-6": "INVERSIONES CONTINENTAL BIO-BIO SPA",
  "076078526-1": "EL MARISCAL SPA",
  "079649140-K": "Gildemeister S.A.",
  "077676964-9": "WICLINIC HOLDING SPA",
  "077741403-8": "INMOBILIARIA SAN AGUSTIN SPA",
  "077815156-1": "INMOBILIARIA PARQUE RINCONADA SPA",
  "077967338-3": "INMOBILIARIA PARQUE TORREONES 5 SPA",
  "096712110-K": "INMOBILIARIA VALLE LA DEHESA S.A.",
  "096762520-5": "CONSTRUCTORA PIE ANDINO S.A.",
  "099591150-7": "INMOBILIARIA SAN LUIS S.A.",
  "096995870-8": "INMOBILIARIA IPL S.A.",
  "076641360-9": "INMOBILIARIA JARDIN DEL CARMEN S.A.",
  "099591350-K": "INMOBILIARIA LOS GAVILANES S.A.",
  "096931030-9": "INMOBILIARIA PARQUE LA LUZ S.A.",
  "076435779-5": "INMOBILIARIA PC 50 S.P.A.",
  "076455471-K": "INMOBILIARIA AGUAPIEDRA S.P.A.",
  "099599540-9": "INMOBILIARIA ALTA VISTA S.A.",
  "096953540-8": "INMOBILIARIA SOL DE MAIPU S.A.",
  "099586380-4": "CONSTRUCTORA E INMOBILIARIA DEL PARQUE S.A.",
  "076954790-8": "INMOBILIARIA LOS CONDORES S.A.",
  "076646780-6": "INMOBILIARIA EL MONTIJO S.A.",
  "099591360-7": "INMOBILIARIA LA HACIENDA DE HUECHURABA S.A.",
  "076349920-0": "INMOBILIARIA LOS AROMOS S.A.",
  "076883240-4": "INMOBILIARIA LOS CIPRESES S.A.",
  "076027704-5": "INMOBILIARIA JARDINES DE CERRILLOS S.A.",
  "076231874-1": "INMOBILIARIA SAN ANTONIO SPA.",
  "077367636-4": "INMOBILIARIA PARQUE TORREONES 4 SPA.",
  "076320057-4": "INMOBILIARIA Y DESARROLLADORA EL REMANSO S.P.A.",
  "099037000-1": "Consorcio Financiero S.A.",
  "096911700-2": "ZURICH SHARED SERVICES",
  "076020595-8": "ZURICH SERVICIOS E INVERSIONES",
  "077750920-9": "Zurich Chile Asset AGF",
  "092723000-3": "Coresa S.A.",
  "093930000-7": "Inmob. Las Condes S.A.",
  "090805000-2": "Grange School S.A.",
  "077355416-1": "LarrainVial AM AGF",
  "076930948-9": "Fintual Frontier AGF",
  "081734800-9": "Automotora Antofagasta",
  "096790570-4": "Unión Golf S.A.",
  "096953460-6": "La Chamisera S.A.",
  "099514870-6": "Metlife Mutuaria S.A.",
  "076253904-7": "Fondo de Inversión Privado Id",
  "099546990-1": "Fondo de Inversión Privado Desarrollo Inmobiliario",
  "076423558-4": "Fintual Frontier AGF",
  "099558780-7": "CEM AGF",
  "097015000-5": "BSANTANDER",
  "076507823-7": "INMOBILIARIA PARQUE EL RODEO",
  "077006218-7": "ITAHUE RAICES SPA",
  "077611170-8": "INMOBILIARIA SECURITY ONCE SPA",
  "077441660-9": "INMOBILIARIA SECURITY NUEVE SPA",
  "099584690-K": "INMOBILIARIA ALTO LO MATTA SPA",
  "090129000-8": "Country Club S.A."
};

window.NEMO_NAME_MAP = {
  "LTM": "LATAM Airlines (LTM)",
  "CHILE": "Banco de Chile S.A.",
  "FALABELLA": "Falabella S.A.",
  "SMU": "SMU S.A.",
  "COPEC": "Copec S.A.",
  "RIPLEY": "Ripley Corp S.A.",
  "COLBUN": "Colbún S.A.",
  "CENCOSUD": "Cencosud S.A.",
  "PARAUCO": "Parque Arauco S.A.",
  "QUINENCO": "Quiñenco S.A.",
  "MALLPLAZA": "Mall Plaza S.A.",
  "CAP": "CAP S.A.",
  "CCU": "CCU S.A.",
  "ECL": "Enel Américas S.A. (ECL)",
  "CMPC": "CMPC S.A.",
  "CONCHATORO": "Viña Concha y Toro S.A.",
  "ANDINA-B": "Andina S.A.",
  "AGUAS-A": "Aguas Andinas S.A.",
  "CENCOMALLS": "Cencosud Shopping S.A.",
  "BCI": "Banco BCI S.A.",
  "CFIMGSIA-E": "Zurich FI MGS I A-E",
  "CFIARR": "Asset Chile Renta Residencial",
  "CFIHMI3R-E": "HMC FI HMI3 R-E",
  "CFIAMRCA-E": "Ameris Parauco A",
  "CFIAMRRE-E": "Ameris Renta Residencial E",
  "CFIBTGFGIA": "BTG FI Global Infrastructure A",
  "CFIDEU2B-E": "LarrainVial RV Deuda 2 B-E",
  "CFIAEAA-E": "LarrainVial Activos Equity A A-E",
  "CFILVOPO-E": "VolcomCapital Oportunidades E",
  "ENJOY": "Enjoy S.A.",
  "NORTEVERDE": "Norteverde S.A.",
  "ACCINPLUNA": "Inmobiliaria Pedro Luna S.P.A.",
  "ENELAM": "Enel Américas S.A.",
  "CFIDHS2-A": "LarrainVial Activos DHS2 A",
  "CFIBIRIA-E": "BICE FI Renta Industrial A E",
  "CFIBTGRCA": "BTG FI Renta Comercial A",
  "CFIBTGRRI": "BTG FI Renta Residencial I",
  "CFIBPDPI2I": "BTG FI Deuda Privada II I",
  "CFIFTSBA-E": "Frontier FI TSB A-E",
  "CFIBTGFGII": "BTG FI Global Infrastructure I",
  "CFICLID4-E": "Principal FI CLID4 E",
  "CFI-WEG4AE": "WEG FI 4 A-E",
  "CFINFRA5-E": "Las Américas FI Infraestructura 5 E",
  "CFIVOBDP-E": "LarrainVial RV Valor Obt. DP E",
  "CFIFTMPI-E": "Frontier FI TMP I-E",
  "CFIFTIAA-E": "Frontier FI TIA A-E",
  "CFIRIADA-E": "Asset Chile FI RIADA E",
  "CFINVIDB-E": "Nvida FI B-E",
  "CFIPFINDESI1": "Avocado FIP Desi 1",
  "CFIPFINVALPL": "Avocado FIP ValPL",
  "CFILVRECIB": "VolcomCapital Recibos B",
  "CFIADI6I": "Ameris BIM Diversificado 6 I",
  "CFIBTGDPIC": "BTG FI Deuda Privada C",
  "CFIPAMERISPREF": "Ameris BIM Preferente (Portafolio)",
  "CFI-RTEIE": "Zurich FI RTE I E",
  "CFIPAMERBIMCAP": "Ameris BIM Capital (Portafolio Ind.)",
  "CFICDR2A": "Compass FI CDR2 A",
  "CFIFTSBP-E": "Frontier FI TSB P-E",
  "CFIPFINAVOCA": "Avocado FIP A",
  "CFIAMSLPI": "Ameris BIM Slp I",
  "CFIAMUPC-E": "Ameris UPC Desarrollo Inmobiliario",
  "CFIPWELLCOT1": "FIP Wellington Cotizado 1",
  "CFIBPDPI-E": "BTG FI Deuda Privada I",
  "CFINRENTAS": "Renta Nacional FI Rentas",
  "CFICELDI2": "BTG FI CEL Deuda Inmob. 2",
  "CFIPFINAVOCB": "Avocado FIP B",
  "CFIAMRCP-E": "Ameris Parauco P",
  "CFIXACTB-E": "XtraConomy ACT B E",
  "CFILCPIS-E": "LarrainVial AM CPI S E",
  "CFIBIINM5": "BICE FI Inmobiliario 5",
  "CFICCH2F-E": "Moneda FI CCH2 F E",
  "CFIBILOG1": "BICE FI Logística 1",
  "CFICAPCA-E": "CADCA FI Cap CA E",
  "CFICCRPB-E": "Moneda FI CCR PB E",
  "CFISANDP-E": "Santander FI DP E",
  "CFIIMTACII": "CFIIMTACII",
  "CINTAC": "Cintac S.A.",
  "DCV-VIDA": "DCV Vida S.A. (alt.)",
  "INTASA": "Intasa S.A.",
  "SQM-B": "SQM S.A.",
  "NORTEGRAN": "NorteGrande S.A.",
  "CALICHERA": "Soc. de Inv. Oro Blanco (Calichera)",
  "ORO BLANCO": "Oro Blanco S.A.",
  "NITRATOS": "Nitratos y Fertilizantes S.A.",
  "CFIMBD4I-E": "MBI FI MD4 I-E",
  "CFILFRPP-E": "LarrainVial AM Renta Fija PP E",
  "CFIMBD3I-E": "MBI FI MD3 I-E",
  "CFITNC2A-E": "Toesca NC2 A E",
  "CFINRAICES": "FI Nac. Raíces (sin AGF)",
  "VIVO STGO": "Vivo Santiago S.A.",
  "NUEVA CHAMISERO": "Nueva Chamisera S.A.",
  "IIS SA": "Inversiones Inmobiliarias Seguras S.A.",
  "PLAZA GRANADILLA": "Plaza Granadilla S.A.",
  "DOCTOR SIERRA": "Doctor Sierra S.A.",
  "BSANTANDER": "BSANTANDER",
  "EGECO": "Egeco S.A.",
  "MONTEMAR": "Montemar Marítima S.A.",
  "ENELCHILE": "Enel Chile S.A.",
  "ITAUCL": "Itaú CorpBanca S.A.",
  "ENTEL": "Entel S.A.",
  "IAM": "IAM S.A.",
  "VAPORES": "Empresa Nav. Vapores S.A.",
  "SALFACORP": "Salfacorp S.A.",
  "CFIETFCC": "LarrainVial FI ETF CC",
  "CFIAINFA-E": "Ameris Infraestructura A E",
  "CFILCPII-E": "LarrainVial AM CPII E",
  "CFICLI3A-E": "Principal FI CLI3 A-E",
  "CFIEUROI-E": "Banchile FI Euro I E",
  "CFINFGLB-E": "Las Américas FI Infraestructura Global E",
  "CFI-APIP1E": "Zurich FI APIP1 E",
  "CFITINGV-E": "Toesca Infraestructura GV E",
  "CFIPIONERO": "Principal FI Pionero (CUI)",
  "CFI-APISE": "Zurich FI APIS E",
  "CFI-CADCAE": "CADCA FI E",
  "FIP ACONCAGUA-CONFUTURO II": "FIP Aconcagua-Confuturo II",
  "CFICCRSI-E": "Moneda FI CCR SI E",
  "CFIARRAB-E": "LarrainVial Arrenta AB E",
  "CFIFALCTAC": "Compass FI FAL CTAC",
  "CFICDR3A-E": "Compass FI CDR3 A-E",
  "CFIERNCI-E": "LarrainVial AM Ern CI E",
  "CONFUTURO  EURO FI PRIVADO": "Confuturo Euro FI Privado",
  "CFIBTGVD3I": "BTG FI Venture Debt 3 I",
  "FIP ANDES III": "FIP Andes III",
  "CFIQAC": "QAC FI",
  "CFIMPIPI-E": "Zurich FI MPI PI E",
  "CFIBTGTE-E": "BTG FI Tecnología E",
  "CFICSUBI-E": "Moneda FI CS UBI E",
  "FIS 2.0": "Ameris BIM FIS 2.0",
  "CFINR8A-E": "Nevasa FI NR8 A-E",
  "CFIQDIA": "QAC FI DIA",
  "FIS 3.0": "Ameris BIM FIS 3.0",
  "CFI-APIP2E": "Zurich FI APIP 2 E",
  "CFI-BCERP1": "Banchile FI CER P1",
  "CFI-RTEBE": "Zurich FI RTE B E",
  "INM VALLE DEL MAR": "Inmobiliaria Valle del Mar",
  "CFIFTIAB-E": "Frontier FI TIA B-E",
  "CFIAMRCI-E": "Ameris Parauco FI-I",
  "CFICCI2B-E": "Moneda FI CCI2 B-E",
  "CFIBDXIA-E": "BCI FI Deuda Extra A-E",
  "CFIAMUPC": "Ameris UP Capital",
  "CFICCRES-E": "Moneda FI CCR ES E",
  "CFIDXIIA-E": "BCI FI Deuda Extra II A-E",
  "CFICCREB-E": "Moneda FI CCR EB E",
  "CFIBCIDESX": "BCI FI Deuda Extra",
  "CFIBCIVIZC": "BCI FI Vizcacha",
  "ALMENDRAL": "Almendral S.A.",
  "INMOBILIARIA ESTOCOLMO FORTALEZA SPA.": "INMOBILIARIA ESTOCOLMO FORTALEZA SPA.",
  "PUCOBRE": "Pucobre S.A.",
  "INMOBILIARIA SANTA MONICA S.P.A.": "INMOBILIARIA SANTA MONICA S.P.A.",
  "CFISMB4I-E": "VolcomCapital SMB 4 I-E",
  "CFIFTRPE-A": "Frontier FI TR PE A",
  "CFINNLC3-E": "Nevasa FI NLC3 E",
  "CFILVCHI-I": "VolcomCapital Chile I",
  "CFICGDRA-E": "Compass FI CGDR A-E",
  "CFILVFA-L": "VolcomCapital FA L",
  "CFICPE2": "BTG FI CP Empresas 2",
  "CFISMB4A-E": "VolcomCapital SMB 4 A-E",
  "CFIPRMINF2": "Principal FI Infraestructura 2",
  "CFIPRMINF": "Principal FI Infraestructura",
  "CFILVSCC-O": "VolcomCapital SCC O",
  "PAGF": "PAGF Penta AGF",
  "CFILVP1I-E": "LarrainVial Activos VP1 I-E",
  "CFITRIAP-E": "Toesca Renta Industrial AP E",
  "CFILVP2A-E": "LarrainVial Activos VP2 A-E",
  "CFITINSC-E": "Toesca Infraestructura SC E",
  "CFITOERI1I": "Toesca OER I I",
  "CFITRIPT-E": "Toesca Renta Inmobiliaria PT E",
  "CFIDHS1": "LarrainVial Activos DHS1",
  "CFIARCVP-E": "Asset Chile Renta Comercial VP E",
  "CFITOERRI": "Toesca OER RI",
  "CFICCACI-E": "Moneda FI CCA CI E",
  "CFIPRREOEI": "PAGF / Penta FI Reo EI",
  "CFICDR2P": "Compass FI CDR2 P",
  "CFIADVSU-E": "Ameris Deuda Diversificada SU E",
  "CFIARCVS-E": "Asset Chile Renta Comercial VS E",
  "CFIREMERGE": "BTG FI Re-Emerge",
  "INM ECOMAC N7": "INM ECOMAC N7",
  "INV SEGURA": "Inversiones Inmobiliarias Seguras S.A.",
  "PIEDRAROJA": "Piedra Roja Desarrollos S.A.",
  "INM IRARRAZAVAL": "INM IRARRAZAVAL",
  "INMOBILIARIA LF SPA": "INMOBILIARIA LF SPA",
  "INM MACKENNA": "INM MACKENNA",
  "INM VINEDOS BUIN": "INM VINEDOS BUIN",
  "INM VICMACK": "INM VICMACK",
  "INM BBI": "INM BBI",
  "INM LA CASTELLANA": "INM LA CASTELLANA",
  "INM ROBLES": "INM ROBLES",
  "PLGRANADILLA": "Plaza Granadilla S.A.",
  "INM MIRAFLORES": "INM MIRAFLORES",
  "INM ZANARTU": "INM ZANARTU",
  "INM RRIO": "INM RRIO",
  "INM VILENA": "INM VILENA",
  "INM LOMAS QUILIN": "INM LOMAS QUILIN",
  "INM ECOMAC N16": "INM ECOMAC N16",
  "INM ECOMAC N1": "INM ECOMAC N1",
  "INM VVALDE": "INM VVALDE",
  "DCV VIDA": "DCV Vida S.A. (alt.)",
  "INM ED VICTORIA": "INM ED VICTORIA",
  "ILC": "ILC S.A.",
  "CFITINFR1I": "Toesca Infraestructura FRI I",
  "CFINFR2": "Las Américas FI Infraestructura 2",
  "CFINFGLB": "Las Américas FI Infraestructura Global",
  "CFIGIII1-E": "Zurich FI GIII 1-E",
  "CFIBIINM4": "BICE FI Inmobiliario 4",
  "CFIRERI-E": "Zurich FI RER I E",
  "CFIMRCLP": "Zurich FI MR CLP",
  "CFICGDIMUA": "Compass FI CGD Inmob. MUA",
  "ECOMAC I": "Independencia ECOMAC I",
  "CFILCPCI-E": "LarrainVial AM CPCI E",
  "CFIHMCIP2I": "HMC FI HMCIP2 I",
  "CFIBPVDIIA": "BTG FI Portafolio Vivienda II A",
  "CFILCPIN-E": "LarrainVial AM CPIN E",
  "CFILBKI2-E": "LarrainVial BKI 2 E",
  "CFICDIMUPF": "Compass FI CDI MUP F",
  "CFIBRENTA": "BICE FI Renta",
  "ECOMAC V": "Independencia ECOMAC V",
  "CFIBIER": "BICE FI Renta (serie alt.)",
  "CFIBTGDPIB": "BTG FI Deuda Privada B",
  "ECOMAC III": "Independencia ECOMAC III",
  "ENLASA": "Enlasa Generación S.A.",
  "RSANPEDRO": "Río San Pedro S.A.",
  "NUCLTRAPEN": "Nucleo Trapezoidal S.A.",
  "TORREMAYOR": "Torremayorv S.A.",
  "EMBONOR-B": "Embonor S.A.",
  "BICE": "BICE S.A.",
  "EXYNKO": "Exynko S.A.",
  "PLAZAEGANA": "Plaza Egaña S.A.",
  "PENTAMH": "Penta MH S.A.",
  "CFIPDEUDAP": "Independencia FIP Deuda Priv.",
  "CFIPAPOQUINDO": "Independencia FIP Apoquindo",
  "CFIPGMANN": "Independencia FIP Gütermannstraße",
  "CFIPKMADEP": "KMA FIP Depto.",
  "CFISANRR-I": "Santander FI Rentas RR I",
  "FIPASSEROT": "Asset Chile FIP Asserot",
  "CFIADGHI": "Ameris Financiamiento Acceso Vivienda I",
  "CFIROSEB-E": "Fynsa FI Rosen B E",
  "CFIPRRESCHI": "Independencia FIP Res. Chile",
  "CFIXDPIA-E": "XtraConomy DPI A E",
  "CFIBDPRP-E": "Banchile FI Deuda Privada P E",
  "CFIFYNSAEC": "Fynsa FI EC",
  "CFIXACTD-E": "XtraConomy ACT D E",
  "CFIXMIXD-E": "XtraConomy MIX D E",
  "CFIAMBIM": "Ameris BIM (Portafolio Ind.)",
  "CFINFR2-E": "Las Américas FI Infra 2-E",
  "CFIXMIXC-E": "XtraConomy MIX C E",
  "CFIIPA": "Independencia FIP IPA",
  "CFIIPA-C": "Independencia FIP IPA-C",
  "CFIAFIMB-E": "Megacentro Buenaventura FI",
  "CFIDEU6U-E": "LarrainVial RV Deuda 6 U-E",
  "CFIAMDDI-E": "Ameris Deuda Dinero I E",
  "CFIADI6FIB": "Ameris Deuda Inmobiliaria VI B",
  "CFIFYNDIII": "Fynsa FI Deuda Inmobiliaria III",
  "CFIPVIDPAR": "HMC FIP Vida Parque",
  "CFIPDRCLII": "Independencia FIP Derc CL II",
  "CFINFUNDA": "CADCA FI Funda",
  "CFIPDRCL": "Independencia FIP Derc CL",
  "CFILCEUP-E": "LarrainVial AM CEU P E",
  "CFIPREMANQ": "Independencia FIP Remanquil",
  "CFIPILUMINA": "Independencia FIP Ilumina",
  "CFIHMI3I-E": "HMC FI HMI3 I-E",
  "CFILCPCH-E": "LarrainVial AM CP Chile E",
  "CFISEPRF-E": "Security FI Capital Pref III FO E",
  "CFICCI2I-E": "Moneda FI CCI2 I E",
  "CFINR17C-E": "Nevasa FI NR17 C-E",
  "CFI-TRAGIE": "Toesca Renta Agrícola I E",
  "CFILCPIP-E": "LarrainVial AM CPI P E",
  "CFICEM2-E": "CEM FI 2 E",
  "CFICAREC-E": "CADCA FI Renta EC E",
  "CFINR10A-E": "Nevasa FI NR10 A-E",
  "CFICAPRP-E": "CADCA FI Cap RP E",
  "CFIAMRRP-E": "Ameris Renta Residencial P-E",
  "CFIGRC3I-E": "Zurich FI GRC3 I-E",
  "CFIFYNSAD1": "Fynsa FI Diversificado 1",
  "CFIPNOGAL": "FIP El Nogal",
  "CFITDPSI-E": "Toesca Deuda Privada SI E",
  "CFIBACHPLU": "Banchile FI Plus",
  "CFIFTDMI-E": "Frontier FI TDM I-E",
  "CFIPKMAMAC": "KMA FIP Mac",
  "CFIOF6A-E": "Nevasa FI OF6 A-E",
  "CFICAPUE-E": "CADCA FI Cap UE E",
  "CFIADIXP-E": "Ameris Desarrollo Inmobiliario IX P",
  "CFIBPDPE-E": "BTG FI Deuda Privada E",
  "CFIAMYPI-E": "CFIAMYPI-E",
  "CFIERNCF-E": "LarrainVial AM Ern CF E",
  "CFIPESTORIL": "FIP Estoril",
  "CFIHMI4I-E": "HMC FI HMI4 I-E",
  "CFIPKMAMAC-A": "KMA FIP Mac A",
  "CFIPDESMAI1": "Independencia FIP Desarrollo Mai 1",
  "CFIBTGCYFI": "BTG FI Core & Yield Fixed Income",
  "CFIEQAUI-E": "LarrainVial Activos Equity UI E",
  "CFIAMS2-E": "Ameris Sindicado Dólar 2",
  "CFIIPA-A": "Independencia FIP IPA-A",
  "CFI-TPC2AE": "Toesca PC2 A E",
  "CFIPSB2CO-PV": "Independencia FIP SB2 CO PV",
  "CFIMCRIA-E": "Ameris MC Renta Industrial A",
  "CFILVDRA-I": "VolcomCapital Deuda RA I",
  "CFINFR4-E": "Las Américas FI Infra 4-E",
  "FIPFENVENII": "FIP FEN Ventures II",
  "CFICCAC2-E": "CFICCAC2-E",
  "CFIMGSIB-E": "Zurich FI MGS I B-E",
  "CFIHYUF-I": "VolcomCapital HYU F I",
  "CF SEGUROS DE VIDA S.A.": "CF Seguros de Vida S.A.",
  "CFISURI3": "SURA FI Renta Inmobiliaria III",
  "CFILVPARI1": "LarrainVial Renta Parisina I",
  "INVERSIONES INMOBILIARIAS SEGURAS S.A.": "Inversiones Inmobiliarias Seguras S.A.",
  "GILDEMEISTER": "Gildemeister S.A.",
  "INMOBILIARIA JARDINES DE CERRILLOS S.A.": "INMOBILIARIA JARDINES DE CERRILLOS S.A.",
  "PIEDRA ROJA DESARROLLOS INMOBILIARIOS S.A.": "Piedra Roja Desarrollos S.A.",
  "INMOBILIARIA PC 50 S.P.A.": "INMOBILIARIA PC 50 S.P.A.",
  "ABC": "ABC DINA S.A.",
  "INMOBILIARIA LOS CIPRESES S.A.": "INMOBILIARIA LOS CIPRESES S.A.",
  "INMOBILIARIA Y DESARROLLADORA EL REMANSO S.P.A.": "INMOBILIARIA Y DESARROLLADORA EL REMANSO S.P.A.",
  "INMOBILIARIA ALTO TABANCURA SPA": "INMOBILIARIA ALTO TABANCURA SPA",
  "INMOBILIARIA LOS CONDORES S.A.": "INMOBILIARIA LOS CONDORES S.A.",
  "INMOBILIARIA VALLE LA DEHESA S.A.": "INMOBILIARIA VALLE LA DEHESA S.A.",
  "INVERSIONES EL PINAR SPA": "INVERSIONES EL PINAR SPA",
  "INMOBILIARIA SAN ANTONIO SPA.": "INMOBILIARIA SAN ANTONIO SPA.",
  "INMOBILIARIA EDIFICIOS DE HACIENDA S.P.A.": "INMOBILIARIA EDIFICIOS DE HACIENDA S.P.A.",
  "INMOBILIARIA VILLA PACIFICO S.P.A.": "INMOBILIARIA VILLA PACIFICO S.P.A.",
  "INVERSIONES CONTINENTAL BIO-BIO SPA": "INVERSIONES CONTINENTAL BIO-BIO SPA",
  "INMOBILIARIA SANTA MARTA S.P.A.": "INMOBILIARIA SANTA MARTA S.P.A.",
  "WICLINIC HOLDING SPA": "WICLINIC HOLDING SPA",
  "INMOBILIARIA EL MONTIJO S.A.": "INMOBILIARIA EL MONTIJO S.A.",
  "EL MARISCAL SPA": "EL MARISCAL SPA",
  "INMOBILIARIA DIEGO DE ALMAGRO SPA": "INMOBILIARIA DIEGO DE ALMAGRO SPA",
  "INMOBILIARIA AGUAPIEDRA S.P.A.": "INMOBILIARIA AGUAPIEDRA S.P.A.",
  "INMOBILIARIA QUEBRADA CLARA SPA": "INMOBILIARIA QUEBRADA CLARA SPA",
  "INMOBILIARIA PEDRO LUNA S.P.A.": "Inmobiliaria Pedro Luna S.P.A.",
  "INMOBILIARIA PARQUE RINCONADA SPA": "INMOBILIARIA PARQUE RINCONADA SPA",
  "INMOBILIARIA LOS AROMOS S.A.": "INMOBILIARIA LOS AROMOS S.A.",
  "INMOBILIARIA ALTO RELONCAVI S.A.": "INMOBILIARIA ALTO RELONCAVI S.A.",
  "INMOBILIARIA LOS ROBLES S.P.A.": "INMOBILIARIA LOS ROBLES S.P.A.",
  "INMOBILIARIA PARQUE TORREONES 4 SPA.": "INMOBILIARIA PARQUE TORREONES 4 SPA.",
  "INMOBILIARIA AGUAS CLARAS S.P.A.": "INMOBILIARIA AGUAS CLARAS S.P.A.",
  "DCV": "DCV Vida S.A. (alt.)",
  "INMOBILIARIA VICENTE VALDES S.A.": "INMOBILIARIA VICENTE VALDES S.A.",
  "INMOBILIARIA PARQUE TORREONES 5 SPA": "INMOBILIARIA PARQUE TORREONES 5 SPA",
  "CONSTRUCTORA E INMOBILIARIA DEL PARQUE S.A.": "CONSTRUCTORA E INMOBILIARIA DEL PARQUE S.A.",
  "INMOBILIARIA PARQUE TORREONES S.P.A.": "INMOBILIARIA PARQUE TORREONES S.P.A.",
  "INMOBILIARIA SAN AGUSTIN SPA": "INMOBILIARIA SAN AGUSTIN SPA",
  "ABC-OSA": "ABC DINA S.A.",
  "INMOBILIARIA VIA PONIENTE S.A.": "INMOBILIARIA VIA PONIENTE S.A.",
  "INMOBILIARIA SOL DE MAIPU S.A.": "INMOBILIARIA SOL DE MAIPU S.A.",
  "INMOBILIARIA PARQUE LA LUZ S.A.": "INMOBILIARIA PARQUE LA LUZ S.A.",
  "INMOBILIARIA PRIMEPARK CURAUMA S.P.A.": "INMOBILIARIA PRIMEPARK CURAUMA S.P.A.",
  "INMOBILIARIA MONTE SANTO 3 S.P.A.": "INMOBILIARIA MONTE SANTO 3 S.P.A.",
  "MATRIZ PLAZA EGANA S.P.A.": "Plaza Egaña S.A.",
  "INMOBILIARIA IPL S.A.": "INMOBILIARIA IPL S.A.",
  "INMOBILIARIA LOS GAVILANES S.A.": "INMOBILIARIA LOS GAVILANES S.A.",
  "INMOBILIARIA LA HACIENDA DE HUECHURABA S.A.": "INMOBILIARIA LA HACIENDA DE HUECHURABA S.A.",
  "INMOBILIARIA LOS NAVEGANTES S.A.": "INMOBILIARIA LOS NAVEGANTES S.A.",
  "INMOBILIARIA ALTA VISTA S.A.": "INMOBILIARIA ALTA VISTA S.A.",
  "INMOBILIARIA JARDIN DEL CARMEN S.A.": "INMOBILIARIA JARDIN DEL CARMEN S.A.",
  "DESARROLLOS INDUSTRIALES TRES SPA.": "DESARROLLOS INDUSTRIALES TRES SPA.",
  "INMOBILIARIA SAN LUIS S.A.": "INMOBILIARIA SAN LUIS S.A.",
  "CONSTRUCTORA PIE ANDINO S.A.": "CONSTRUCTORA PIE ANDINO S.A.",
  "CFI-MBICHI": "MBI FI Chile I",
  "CFIFTF13-A": "Frontier FI TF13 A",
  "CFINCIMENT": "Inciment FI",
  "CFIGIII4-E": "Zurich FI GIII 4-E",
  "CFIFTXXB-E": "Frontier FI TXX B-E",
  "CFIWEG-2E": "WEG FI 2 E",
  "CFICRR3U-E": "Moneda FI CRR3 U-E",
  "CFIADPVI-E": "Ameris DP Vivienda I E",
  "CFIWEG-1": "WEG FI 1",
  "CFIFTF13-B": "Frontier FI TF13 B",
  "ZURICH CHILE ASSET AGF": "ZURICH CHILE ASSET AGF",
  "CONSOGRAL": "Consorcio Financiero S.A.",
  "CORESA": "Coresa S.A.",
  "DCV VIDA S.A.": "DCV Vida S.A. (alt.)",
  "ZURICH SERVICIOS E INVERSIONES": "ZURICH SERVICIOS E INVERSIONES",
  "ZURICH SHARED SERVICES": "ZURICH SHARED SERVICES",
  "CFIIMSCLI": "Moneda FI IMS CLI",
  "CFIEACICUI": "Zurich ORO Diario (CUI)",
  "SQM-A": "SQM S.A.",
  "LAS CONDES": "Inmob. Las Condes S.A.",
  "GRANGE-B": "Grange School S.A.",
  "CFIXMIXA-E": "XtraConomy MIX A-E",
  "CFIXACTC-E": "XtraConomy ACT C-E",
  "CFICPE2-E": "BTG FI CP Empresas 2-E",
  "CFICAP1B-E": "LarrainVial Activos Cap1 B-E",
  "CFIBTGPA-E": "BTG FI Portafolio A-E",
  "CFICPE3-E": "BTG FI CP Empresas 3-E",
  "CFICAP1A-E": "LarrainVial Activos Cap1 A-E",
  "CHAMISERO": "La Chamisera S.A.",
  "METLIFE MUTUARIA": "Metlife Mutuaria S.A.",
  "CLUB UNION G": "Unión Golf S.A.",
  "AUTO ANTOF": "Automotora Antofagasta",
  "CFIPOINDNDI": "Compass FI NDI (Portafolio Ind.)",
  "CFIGIII3-E": "Zurich FI GIII 3-E",
  "CFIBDPR2P": "Banchile FI DP R2P",
  "CFITNC2I-E": "Toesca NC2 I-E",
  "CFICELDI1": "BTG FI CEL Deuda Inmob. 1",
  "INMOBILIARIA SECURITY NUEVE SPA": "INMOBILIARIA SECURITY NUEVE SPA",
  "INMOBILIARIA ALTO LO MATTA SPA": "INMOBILIARIA ALTO LO MATTA SPA",
  "ITAHUE RAICES SPA": "ITAHUE RAICES SPA",
  "INMOBILIARIA PARQUE EL RODEO": "INMOBILIARIA PARQUE EL RODEO",
  "UNION GOLF": "Unión Golf S.A.",
  "INMOBILIARIA SECURITY ONCE SPA": "INMOBILIARIA SECURITY ONCE SPA",
  "COUNTRY CLUB": "Country Club S.A.",
  "CFIPINIDEA2": "Idea Capital FIP 2",
  "CFIXMIXB-E": "XtraConomy MIX B E",
  "CFIBTGRCI": "BTG FI Rentas Comerciales I",
  "CFIFTFEX-E": "Frontier FI TFX E",
  "CFIBAIN10P": "Banchile FI Alternativo 10 P",
  "CFISEDCB-E": "Security FI Des. Comercial Bic. E",
  "CFIAFVVIII": "Ameris FI AFV VIII",
  "CFILV2PT-E": "VolcomCapital LV2 PT-E",
  "CFILVP2B-E": "LarrainVial Activos VP2 B-E",
  "CFISDA3B-E": "Security FI DP Automotriz III B-E",
  "CFIPINIDEA": "Idea Capital FIP",
  "CFISEDUH-E": "Security FI Deuda Hab. UH E",
  "CFIPDESINMOBV": "Desarrollo Inmob. FIP V",
  "CFIAFVVIIA": "Ameris FI AFV VII A",
  "DCVVIDA": "DCV Vida S.A.",
  "INVDCV": "Inversiones DCV S.A.",
  "CFISUREREU": "SURA FI Renta Residencial U",
  "CFIRESURA1": "SURA FI Renta (liquidación)",
  "CFI-SUREGA": "SURA FI Renta GA",
  "CFIBTGFIPI": "BTG FI Portafolio Inmobiliario",
  "CFISUCAINI": "SURA FI Caja Inmobiliaria",
  "CFIBTGVDI": "BTG FI Venture Debt I",
  "CFICDR2A-E": "Compass FI CDR 2 A-E",
  "CFIXLCDI-E": "XtraConomy FI Liquid Credit Discovery I-E",
  "CFIBIINM2": "BICE FI Inmobiliario II",
  "CFIADPI-E": "Ameris FI Deuda Privada I-E",
  "CFITOESC-I": "Toesca FI Estrategia Combinada I",
  "CFIAMLYTPI": "Ameris FI Multi Late-Stage Tech / Private I",
  "CFIFYNMIGG": "Fynsa FI Inversiones Globales",
  "CFICPE3": "BTG FI CPE III",
  "CFINENGI": "LarraínVial FI Nuevas Energías I",
  "CFISANRCI": "Santander FI Renta Comercial I",
  "CFIFRINI-E": "Compass FI Frontier I-E",
  "CFIPALZAKP3A": "Ameris FIP Alzaprima 3 A",
  "CFICDIMU-E": "Compass FI CDI Multi-activo E",
  "CFIPRREOI2": "Penta Las Américas FIP Renta Real Estate Oport. II",
  "CFIXACTA-E": "XtraConomy FI Activa A-E",
  "CFIXMIXE-E": "XtraConomy FI Mixto E",
  "CFICLAI-E": "Moneda FI CLAI E",
  "CFINR16A-E": "Nevasa FI N° 16 A-E",
  "CFILVSCC-U": "VolcomCapital FI Stock Credit Combinada U",
  "CFIPDESINMIII": "IPA FIP Desarrollo Inmobiliario III",
  "CFIPDEINM2": "IPA FIP Desarrollo Inmobiliario II",
  "CFIPDESINM1": "IPA FIP Desarrollo Inmobiliario I",
  "CFIPEDIFICA1": "Penta Las Américas FIP Edifica I",
  "CCFICGDIMUA": "Compass FI CG DIMU A",

  // Ameris — fondos B.2 y B.5 con nombres comerciales (tabla Ameris × Penta Vida 2026-03)
  "CFIPATAAMF-I":  "Ameris Multifamily Partners I",
  "CFIALTEF-E":    "Ameris Alternativos I F",
  "CFIALT2I-E":    "Ameris Alternativos II I",
  "CFIANXII-E":    "Ameris Private Equity Nordic XI I",
  "CFIACESC-E":    "Ameris CESL II C",
  "CFIACE3C-E":    "Ameris CESL III C",
  "CFIAMLGT-E":    "Ameris LGT Secondaries IV",
  "CFIAMG3I-E":    "Ameris NM Private Credit I",
  "CFIAG3IN-E":    "Ameris NM Private Credit IN",
  "CFIASXII-E":    "Ameris Dover Street XI I",
  "CFIAHV7I-E":    "Ameris Harbourvest Co-Investment VII I",
  "CFIANM7I-E":    "Ameris NM Partners VII I",
  "CFIADIPE-E":    "Ameris Desarrollo Inmobiliario Perú"
};
